name: Build
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-debian:
    name: Build ${{ matrix.job.platform }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        job:
          - { platform: linux/arm/v5 }
          - { platform: linux/arm/v7 }
          - { platform: linux/arm64 }
          - { platform: linux/amd64 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - uses: taiki-e/install-action@just

      - name: Patch
        run: just PLATFORM=${{ matrix.job.platform }} patch-debian

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.job.platform }}
          path: debian/dist/*
